name: CD - Deploy with Terraform and ECR

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set image tag from commit SHA
        run: |
          IMAGE_TAG=gh-${GITHUB_SHA::7}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Verify ECR image exists
        run: |
          aws ecr describe-images \
            --repository-name nisha-ecr \
            --image-ids imageTag=${{ env.IMAGE_TAG }} \
            --region us-east-2 > /dev/null || {
              echo "Image with tag $IMAGE_TAG not found in ECR.";
              exit 1;
          }

      - name: Terraform Init
        run: |
          cd terraform_task7
          terraform init -input=false

      - name: Terraform Import Existing Resources
        run: |
          cd terraform_task7

          # terraform import -input=false -var="image_tag=${{ env.IMAGE_TAG }}" aws_cloudwatch_log_group.nisha_strapi /ecs/nisha-strapi
          terraform import -input=false -var="image_tag=${{ env.IMAGE_TAG }}" aws_iam_role.ecs_task_execution_role ecsTaskExecutionRole
          # terraform import -input=false -var="image_tag=${{ env.IMAGE_TAG }}" aws_db_subnet_group.nisha_db_subnet_group nisha-db-subnet-group
          # terraform import -input=false -var="image_tag=${{ env.IMAGE_TAG }}" aws_security_group.nisha_ecs_sg sg-0ae4a4fa845669068
          # terraform import -input=false -var="image_tag=${{ env.IMAGE_TAG }}" aws_lb_target_group.nisha_strapi_tg arn:aws:elasticloadbalancing:us-east-2:607700977843:targetgroup/nisha-strapi-tg/0b7d7975021cd54d
          # terraform import -input=false -var="image_tag=${{ env.IMAGE_TAG }}" aws_lb.nisha_alb arn:aws:elasticloadbalancing:us-east-2:607700977843:loadbalancer/app/nisha/6c3a1447f7861af3
          # terraform import -input=false -var="image_tag=${{ env.IMAGE_TAG }}" aws_lb_listener.http arn:aws:elasticloadbalancing:us-east-2:607700977843:listener/app/nisha/6c3a1447f7861af3/8ccf0374a0a40626
          # terraform import -input=false -var="image_tag=${{ env.IMAGE_TAG }}" aws_ecs_service.nisha_service your-cluster-name/nisha-service
          # terraform import -input=false -var="image_tag=${{ env.IMAGE_TAG }}" aws_ecs_service.nisha_service arn:aws:ecs:us-east-2:607700977843:service/nisha-cluster/nisha-service

      - name: Terraform Plan
        run: |
          cd terraform_task7
          terraform plan -input=false -var="image_tag=${{ env.IMAGE_TAG }}"

      - name: Terraform Apply
        run: |
          cd terraform_task7
          terraform apply -input=false -auto-approve -var="image_tag=${{ env.IMAGE_TAG }}"

      - name: Output Terraform values
        run: |
          echo "Fetching Terraform Outputs..."
          terraform output strapi_url
          terraform output rds_endpoint
