name: CD - Deploy with Terraform

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set image tag from commit SHA
        run: |
          IMAGE_TAG=gh-${GITHUB_SHA::7}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Verify image exists on Docker Hub
        run: |
          echo "Checking image nishanc7/strapi:${{ env.IMAGE_TAG }}"
          curl -s -f -lSL "https://hub.docker.com/v2/repositories/nishanc7/strapi/tags/${{ env.IMAGE_TAG }}/" || {
            echo "Image not found. Make sure CI completed successfully."; exit 1;
          }

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: |
          cd terraform_task5
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform_task5
          terraform plan -var="image_tag=${{ env.IMAGE_TAG }}"

      - name: Terraform Apply
        run: |
          cd terraform_task5
          terraform apply -auto-approve -var="image_tag=${{ env.IMAGE_TAG }}"
