version: "3.8"

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

  strapi:
    build: .
    container_name: strapi
    restart: always
    env_file: .env
    working_dir: /opt/app

    ports:
      - "1337:1337"
    depends_on:
      - postgres
    networks:
      - my-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - strapi
    networks:
      - my-network
