name: Terraform CI

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-2
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Change to Terraform directory
        run: cd terraform_task7

      - name: Terraform Init
        run: terraform -chdir=terraform_task7 init

      - name: Terraform Import Resources
        run: |
          terraform -chdir=terraform_task7 import aws_security_group.nisha_ecs_sg sg-0cf2fc2cb9a7375a0
          terraform -chdir=terraform_task7 import aws_lb_target_group.nisha_strapi_tg arn:aws:elasticloadbalancing:us-east-2:<your_account_id>:targetgroup/nisha-strapi-tg/0b7d7975021cd54d
          terraform -chdir=terraform_task7 import aws_cloudwatch_log_group.nisha_strapi /ecs/nisha-strapi
          terraform -chdir=terraform_task7 import aws_iam_role.ecs_task_execution_role ecsTaskExecutionRole
          terraform -chdir=terraform_task7 import aws_db_subnet_group.nisha_db_subnet_group nisha-db-subnet-group

      - name: Terraform Plan
        run: terraform -chdir=terraform_task7 plan -var="image_tag=${IMAGE_TAG}"

      - name: Terraform Apply
        run: terraform -chdir=terraform_task7 apply -auto-approve -var="image_tag=${IMAGE_TAG}"
