name: CD - Deploy with Terraform

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set image tag from commit SHA
        run: echo "IMAGE_TAG=gh-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Verify image exists on Docker Hub
        run: |
          echo "Checking image nishanc7/strapi:${{ env.IMAGE_TAG }}"
          curl -s -f -lSL "https://hub.docker.com/v2/repositories/nishanc7/strapi/tags/${{ env.IMAGE_TAG }}/" || {
            echo "Image not found. Make sure CI completed successfully."; exit 1;
          }

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform_task5

      - name: Terraform Apply
        run: terraform apply -var="image_tag=${{ github.sha }}"
        working-directory: ./terraform_task5
