name: CD pipeline - Deploy to EC2

on:
  workflow_dispatch:
    inputs:
      sha:
        description: "Git commit SHA (7 characters) used for Docker image tag"
        required: true

env:
  DOCKER_IMAGE_TAG: gh-${{ github.event.inputs.sha }}
  REGISTRY_USER: ${{ vars.DOCKERHUB_USERNAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="image_tag=${{ env.DOCKER_IMAGE_TAG }}"

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
